### ISSUE TITLE
drupal installation on jammy

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/friends_of_pul#137]
### Expected behavior

I expect a deploy to bring the website back up.

### Actual behavior

I get to the website but it looks like it needs the Drupal website to be installed new. 
![Screenshot 2023-04-13 at 1 35 45 PM](https://user-images.githubusercontent.com/685884/231840216-b5acc0ae-a6ba-4b23-a2aa-5ca0d4e480ca.png)

### Steps to replicate

Deploy to the jammy, staging VM

### Impact of this bug

The work around is to copy the `/home/deploy/settings.php` to point to `/var/www/friends_of_pul/current/sites/default/settings.php` - it currently creates a symbolic link. 

### Honeybadger link and code snippet, if applicable

```
```

**Comment by kevinreiss** [comment]
The last bit of housekeeping is the new webfile share needs to be writable by www-data. Right now on the staging site you get errors like: ![Screenshot 2023-07-12 at 8.47.57 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/d1be98ee-3972-44d6-9427-79515375ba6f)

**Comment by kevinreiss** [comment]
Per Francis this is done.
