### ISSUE TITLE
Remove "TBA" from Blank Calendar days

### ISSUE THREAD

**Issue by sdellis** [pulibrary/friends_of_pul#17]

**Comment by kevinreiss** [comment]
This a hack for a behavior desired in the main website calendar. This can just be taken out:

https://github.com/pulibrary/friends_of_pul/blob/1459f32e5d0d295f0661966f8869fe0d955fb51b/sites/all/themes/pul_base/templates/calendar/calendar-week.tpl.php#L51

https://github.com/pulibrary/friends_of_pul/blob/1459f32e5d0d295f0661966f8869fe0d955fb51b/sites/all/themes/pul_base/sass/pul-base.hacks.scss#L58

I'll put in an issue to extract this out of PUL Base and place it somewhere else in the main website codebase.
