### ISSUE TITLE
Add Breadcrumbs ... 

### ISSUE THREAD

**Issue by sdellis** [pulibrary/friends_of_pul#21]
... so that users know when they are in Student Friends vs. regular Friends site sections.  @axapu is there a preferred method for painting breadcrumbs?  It seems like the breadcrumbs regions have been removed from the templates.

**Comment by axamei** [comment]
We removed breadcrumbs on the main site because it was problematic and not fully accurate/helpful. I think we were using panels to handle the breadcrumbs. Is that correct, @kevinreiss?

**Comment by sdellis** [comment]
Ok, gotcha.  Yes, @kevinreiss mentioned that breadcrumbs are generally problematic in Drupal.  I think we will be ok now that I have added an "active" state style to the main menu to indicate what section you're in.  The hierarchy is only one level deep, so I'm going to close this.

**Comment by kevinreiss** [comment]
Yes, we tried the panels_breadcrumbs module. It was okay for what it what is in that you could substitute context values from the current request into the Breadcrumb.

**Comment by kevinreiss** [comment]
However it was always a bit wonky.
