### ISSUE TITLE
Add Announcements Content Type

### ISSUE THREAD

**Issue by sdellis** [pulibrary/friends_of_pul#24]
Most recent Announcement will sit above Events on the home page, with a link to a past Announcements page.  Fields include title, image, body textarea.

**Comment by kevinreiss** [comment]
@sdellis other than "events" is the only other kind of content that would require notifications be distributed to friend or student friend users?

**Comment by axamei** [comment]
Article content type was used for announcements. Created Latest News pane for landing page. Relocated to middle panel. See #47.
