### ISSUE TITLE
Revise User Roles

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/friends_of_pul#26]
Beyond administrator the site needs the following roles. 
1. Officer - Post events/messages to friends
2. Friend - Can subscribe to events/annoucement channels, automatically subscribed to events specifically flagged for friends
3. Student Friend Officer - can post events/annoucements to student friend channels
4. Student Friend - Can subscribe events/annoucement channels, automatically subscribe to student friend events.

**Comment by kevinreiss** [comment]
Existing users should all be filed under friends. Officers/Student friends will be manually assigned.

**Comment by axamei** [comment]
Currently, these are the following roles:
- administrator
- staff
- friends council member

@kevinreiss @sdellis Is "friends council member" the same as "Officer"?

**Comment by kevinreiss** [comment]
I think so.

**Comment by axamei** [comment]
Staff needs to be able to change the role of friends council members
