### ISSUE TITLE
Set Up Messaging Framework

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/friends_of_pul#27]
The site should be able to distribute messaging and notifications about content additions. Users should be able to subscribe to messages. Possible implementation choice:

https://www.drupal.org/node/2180145

**Comment by axamei** [comment]
If possible, some way to easily send mass emails (broadcast-style). Perhaps via Rules module
- [ ] Event reminders and RSVP
- [ ] Mailing list for Student Friends Members
