### ISSUE TITLE
Student Friends Signup

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/friends_of_pul#28]
A form that allows student friends to sign up should be provided. The sign up process should capture name, email, and automatically subscribe them to the default student friend notification channels.

**Comment by axamei** [comment]
New member sign-up:
- [x] Name, class year, email
- [ ] Register students for site upon sign up (manual)
- [ ] Mailing list for Student Friends Members / setup email notifications based on rules

**Comment by axamei** [comment]
Student friends signup form created. Closing. Refer to #27 for messaging framework.
