### ISSUE TITLE
WYSIWYG formatting options not working

### ISSUE THREAD

**Issue by axamei** [pulibrary/friends_of_pul#46]
Basic formatting like centering is not working

**Comment by axamei** [comment]
This might be an issue with the filtered html / full html settings

**Comment by kevinreiss** [comment]
Definitely. Check to make sure the user in question has rights to use the format. I'd actually not give any full html access. I'd make a new filter format, say "Editor HTML" that enables users to use more HTML tags that the basic filtered format which only gives you `<a>, <p>, <img>`, etc.

**Comment by axamei** [comment]
It looks like an issue with "Limit allowed HTML tags" when you toggle it off, the formatting works. Should we filter out the tags with a separate module as this post suggests?  https://www.drupal.org/node/2510970#comment-10068192
